name: "Project Prioritization"
description: ""
author: "Adam Rusted"

inputs:
  repo-token:
    description: "The repo token you'd like to use"
    required: true
    default: ${{ secrets.GITHUB_TOKEN }}
  org:
    description: "The organisation we should look for the project against"
    required: false
  project:
    description: "The number of the project you'd like to add this PR to."
    required: true
  field_name:
    description: "The field we should look to categorise the PR under."
    required: true
    default: Status
  option_name:
    description: "Which option you'd like the PR to sit under"
    required: true
    default: Unprioritised

runs:
  using: "node20"
  main: "dist/index.js"
