name: "Project Prioritization"
description: ""
author: "Adam Rusted"

inputs:
  repo-token:
    description: "The repo token you'd like to use"
    required: true
    default: ${{ github.token }}

runs:
  using: "node20"
  main: "dist/index.js"
